[general]
#output = "icarus_charged_pion_full"
output = "icarus_charged_pion"
primfn = "default_primary_classification"
pidfn = "default_pid"

[[category]] # 0 : Fiducial, single muon, single pion
cuts = [
    { name = "neutrino"        },
    { name = "fiducial_cut"    },
    { name = "no_photons",       parameters = [25.0] },
    { name = "no_electrons",     parameters = [25.0] },
    { name = "single_muon",      parameters = [143.425] },
    { name = "single_pion",    parameters = [25.0] },
]

[[category]] # 1 : Single muon, multiple pion
cuts = [
    { name = "neutrino" },
    { name = "fiducial_cut"    },
    { name = "no_photons",       parameters = [25.0] },
    { name = "no_electrons",     parameters = [25.0] },
    { name = "single_muon",      parameters = [143.425] },
    { name = "!no_charged_pions", parameters = [25.0] },
    { name = "!single_pion",    parameters = [25.0] },
]

[[category]] # 2 : Single muon, zero pion
cuts = [
    { name = "neutrino" },
    { name = "fiducial_cut"    },
    { name = "no_photons",       parameters = [25.0] },
    { name = "no_electrons",     parameters = [25.0] },
    { name = "single_muon",      parameters = [143.425] },
    { name = "no_charged_pions", parameters = [25.0] },
]

[[category]] # 3 : Neutrino, charged current
cuts = [
    { name = "neutrino" },
    { name = "fiducial_cut"    },
    { name = "iscc"     },
]

[[category]] # 4 : Neutrino, neutral current
cuts = [
    { name = "neutrino" },
    { name = "fiducial_cut"    },
    { name = "!iscc"    },
]

[[category]] # 5 : Out of FV
cuts = [
    { name = "!fiducial_cut" },
    { name = "neutrino" },
]

[[category]] # 6 : Cosmic
cuts = [
    { name = "!neutrino" },
]

[[sample]]
name = "nominal"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_CV_flat_cafs_2/NuMI_CV_flat_cafs_2_01.root"
#path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_CV_flat_cafs_2/NuMI_CV_flat_cafs_2_0[0-1].root"
#path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_CV_flat_cafs_2/NuMI_CV_flat_cafs_2_0*.root"
ismc = true
disable = false

[[sample]]
name = "onbeam"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_data_flat_cafs_2/*.root"
ismc = false
disable = false


[[tree]]
name = "selected"
sim_only = false
add_exposure = true
mode = "reco"
cut = [
    { name = "fiducial_cut",              type = "reco" },
    { name = "flash_cut",                 type = "reco",  parameters = [0.0, 9.6] },
    { name = "no_photons",                type = "reco",  parameters = [25.0] },
    { name = "no_electrons",              type = "reco",  parameters = [25.0] },
    { name = "single_muon",               type = "reco",  parameters = [143.425] },
    { name = "single_pion",               type = "reco",  parameters = [25.0] },
    { name = "trigger_emulation_cut",     type = "event", decrements_exposure = false },
    { name = "data_quality_cut",          type = "event", decrements_exposure = true },
]
branch = [
    # Interaction-level truth/reco branches
    { name = "neutrino_id",             type = "true"    },
    { name = "baseline",                type = "mctruth" },
    { name = "cc",                      type = "mctruth" },
    { name = "pdg",                     type = "mctruth" },
    { name = "interaction_type",        type = "mctruth" },
    { name = "interaction_mode",       type = "mctruth" },
    { name = "category",                type = "true"    },
    { name = "neutrino_energy",         type = "mctruth" },
    { name = "photon_multiplicity",     type = "both",    parameters = [25.0,]},
    { name = "electron_multiplicity",   type = "both",    parameters = [25.0,]},
    { name = "muon_multiplicity",       type = "both",    parameters = [143.425,]},
    { name = "pion_multiplicity",       type = "both",    parameters = [25.0,]},
    { name = "proton_multiplicity",     type = "both",    parameters = [50.0,]},
    { name = "selected_pion_ke",     type = "both",    parameters = [25.0,]},
    { name = "selected_muon_ke",     type = "both",    parameters = [143.425,]},

    # Kinematic imbalance & angles
    { name = "opening_angle", type = "both" },
    { name = "hadron_invariant_mass_hadron", type = "both" },
    { name = "dpT",           type = "both" },
    { name = "dpT_lp",        type = "both" },
    { name = "dphiT",         type = "both" },
    { name = "dalphaT",       type = "both" },
    { name = "dpL",           type = "both" },
    { name = "dpL_lp",        type = "both" },
    { name = "pn",            type = "both" },
    { name = "pn_lp",         type = "both" },
    { name = "muon_cos_angle",     type = "both"},
    { name = "pion_cos_angle",     type = "both"},
    { name = "hadron_invariant_mass_general",     type = "both"},
    { name = "is_theresplitmuon",     type = "both"},
    { name = "hadronic_invariant_mass", type = "true" },
    { name = "four_mom_transfer_squared",     type = "both"},
    { name = "q3_transfer",     type = "both"},
    { name = "q0_transfer",     type = "both"},
    { name = "visible_energy",          type = "both"    },
    { name = "visible_energy_calosub",  type = "both"    },


    # Vertex & flash
    { name = "vertex_x",         type = "both" },
    { name = "vertex_y",         type = "both" },
    { name = "vertex_z",         type = "both" },
    { name = "flash_time",       type = "reco" },
    { name = "flash_total_pe",   type = "reco" },
    { name = "flash_hypothesis", type = "reco" },
    { name = "containment",      type = "reco" },
    { name = "fiducial",         type = "reco" },

    # Leading MUON interaction-level
    { name = "end_x",             type = "both_particle", selector = "leading_muon"   },
    { name = "end_y",             type = "both_particle", selector = "leading_muon"   },
    { name = "end_z",             type = "both_particle", selector = "leading_muon"   },
    { name = "end_dir_x",             type = "both_particle", selector = "leading_muon" },
    { name = "end_dir_y",             type = "both_particle", selector = "leading_muon" },
    { name = "end_dir_z",             type = "both_particle", selector = "leading_muon" },
    { name = "start_dir_x",             type = "both_particle", selector = "leading_muon" },
    { name = "start_dir_y",             type = "both_particle", selector = "leading_muon" },
    { name = "start_dir_z",             type = "both_particle", selector = "leading_muon" },
    { name = "ke",                type = "both_particle", selector = "leading_muon"   },
    { name = "length",            type = "both_particle", selector = "leading_muon"   },
    { name = "dpT",               type = "both_particle", selector = "leading_muon" },
    { name = "polar_angle",       type = "both_particle", selector = "leading_muon" },
    { name = "azimuthal_angle",   type = "both_particle", selector = "leading_muon" },
    { name = "cos_wrt_beam",   type = "both_particle", selector = "leading_muon" },
    { name = "containment",   type = "both_particle", selector = "leading_muon" },
    { name = "primary_classification",   type = "both_particle", selector = "leading_muon" },
    { name = "pid",   type = "both_particle", selector = "leading_muon" },

    # Leading PION particle-level
    { name = "end_x",             type = "both_particle", selector = "leading_pion" },
    { name = "end_y",             type = "both_particle", selector = "leading_pion" },
    { name = "end_z",             type = "both_particle", selector = "leading_pion" },
    { name = "end_dir_x",             type = "both_particle", selector = "leading_pion" },
    { name = "end_dir_y",             type = "both_particle", selector = "leading_pion" },
    { name = "end_dir_z",             type = "both_particle", selector = "leading_pion" },
    { name = "start_dir_x",             type = "both_particle", selector = "leading_pion" },
    { name = "start_dir_y",             type = "both_particle", selector = "leading_pion" },
    { name = "start_dir_z",             type = "both_particle", selector = "leading_pion" },
    { name = "ke",                type = "both_particle", selector = "leading_pion" },
    { name = "length",            type = "both_particle", selector = "leading_pion" },
    { name = "dpT",               type = "both_particle", selector = "leading_pion" },
    { name = "polar_angle",       type = "both_particle", selector = "leading_pion" },
    { name = "cos_wrt_beam",   type = "both_particle", selector = "leading_pion" },
    { name = "azimuthal_angle",   type = "both_particle", selector = "leading_pion" },
    { name = "containment",   type = "both_particle", selector = "leading_pion" },
    { name = "primary_classification",   type = "both_particle", selector = "leading_pion" },
    { name = "pid",   type = "both_particle", selector = "leading_pion" },
    { name = "directional_spread",   type = "reco_particle", selector = "leading_pion" },
    { name = "kink_cos_angle",   type = "true_particle", selector = "leading_pion" },
]



[[tree]]
name = "signal"
sim_only = true
add_exposure = true
mode = "true"
cut = [
    { name = "neutrino",              type = "true" },
    { name = "fiducial_cut",          type = "true" },
    { name = "no_photons",            type = "true",  parameters = [25.0] },
    { name = "no_electrons",          type = "true",  parameters = [25.0] },
    { name = "single_muon",           type = "true",  parameters = [143.425] },
    { name = "single_pion",           type = "true", parameters = [25.0] },
    { name = "trigger_emulation_cut", type = "event", decrements_exposure = false },
]
branch = [
    # Interaction-level truth branches
    { name = "neutrino_id",            type = "true"    },
    { name = "containment_cut",        type = "both"    },
    { name = "fiducial_cut",           type = "both"    },
    { name = "baseline",               type = "mctruth" },
    { name = "cc",                     type = "mctruth" },
    { name = "pdg",                    type = "mctruth" },
    { name = "interaction_mode",       type = "mctruth" },
    { name = "interaction_type",       type = "mctruth" },
    { name = "category",               type = "true"    },
    { name = "neutrino_energy",        type = "mctruth" },
    { name = "visible_energy",         type = "both"    },
    { name = "visible_energy_calosub", type = "true"    },

    # Interaction-level selection variables
    { name = "photon_multiplicity",   type = "reco", parameters = [25.0,]},
    { name = "electron_multiplicity", type = "reco", parameters = [25.0,]},
    { name = "muon_multiplicity",     type = "reco", parameters = [25.0,]},
    { name = "pion_multiplicity",     type = "reco", parameters = [143.425,]},
    { name = "proton_multiplicity",   type = "reco", parameters = [50.0,]},
    { name = "flash_time",            type = "reco" },
    { name = "selected_pion_ke",     type = "both",    parameters = [25.0,]},
    { name = "selected_muon_ke",     type = "both",    parameters = [143.425,]},

    # Kinematic imbalance & angles
    { name = "opening_angle", type = "both" },
    { name = "dpT",           type = "both" },
    { name = "dpT_lp",        type = "both" },
    { name = "dphiT",         type = "both" },
    { name = "dalphaT",       type = "both" },
    { name = "dpL",           type = "both" },
    { name = "dpL_lp",        type = "both" },
    { name = "pn",            type = "both" },
    { name = "pn_lp",         type = "both" },
    { name = "muon_cos_angle",     type = "both"},
    { name = "pion_cos_angle",     type = "both"},
    { name = "four_mom_transfer_squared",     type = "both"},
    { name = "hadron_invariant_mass_hadron", type = "both" },
    { name = "hadron_invariant_mass_general",     type = "both"},
    { name = "hadronic_invariant_mass", type = "true" },

    # True-vertex
    { name = "vertex_x", type = "true" },
    { name = "vertex_y", type = "true" },
    { name = "vertex_z", type = "true" },

    # Leading MUON particle-level
    { name = "end_x",             type = "both_particle", selector = "leading_muon" },
    { name = "end_y",             type = "both_particle", selector = "leading_muon" },
    { name = "end_z",             type = "both_particle", selector = "leading_muon" },
    { name = "ke",                type = "both_particle", selector = "leading_muon" },
    { name = "length",            type = "both_particle", selector = "leading_muon" },
    { name = "dpT",               type = "both_particle", selector = "leading_muon" },
    { name = "polar_angle",       type = "both_particle", selector = "leading_muon" },
    { name = "azimuthal_angle",   type = "both_particle", selector = "leading_muon" },
    { name = "containment",   type = "both_particle", selector = "leading_muon" },
    { name = "cos_wrt_beam",   type = "both_particle", selector = "leading_muon" },
    { name = "primary_classification",   type = "both_particle", selector = "leading_muon" },
    { name = "pid",   type = "both_particle", selector = "leading_muon" },

    # Leading PION particle-level
    { name = "end_x",             type = "both_particle", selector = "leading_pion" },
    { name = "end_y",             type = "both_particle", selector = "leading_pion" },
    { name = "end_z",             type = "both_particle", selector = "leading_pion" },
    { name = "ke",                type = "both_particle", selector = "leading_pion" },
    { name = "length",            type = "both_particle", selector = "leading_pion" },
    { name = "dpT",               type = "both_particle", selector = "leading_pion" },
    { name = "polar_angle",       type = "both_particle", selector = "leading_pion" },
    { name = "azimuthal_angle",   type = "both_particle", selector = "leading_pion" },
    { name = "cos_wrt_beam",   type = "both_particle", selector = "leading_pion" },
    { name = "containment",   type = "both_particle", selector = "leading_pion" },
    { name = "primary_classification",   type = "both_particle", selector = "leading_pion" },
    { name = "pid",   type = "both_particle", selector = "leading_pion" },
]
