[general]
output = "data_quality"

[[include_samples]]
file = "common/osc.toml"
keys = [
    "sbnd_offbeam",
    "icarus_offbeam_run4",
]

[[tree]] # No cut nreco for DQ
name = "noCut_nreco"
sim_only = false
mode = "event"
cut = [
    { name = "no_cut", type = "event" },
]
branch = [
    { name = "nreco", type = "event" },
]